# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b027522c1b74ac6fe46487c5a58119a4cb7bda2628b8d51f2637bb9cb54b2bd004f264efffdf80b42249e96276747b8d903d1521e0e661c903d279b4231a31d

test:
  secret_key_base: 08f135a31ff7814d1e994cd7a697a716236459013be9205e2b2f222c141432b63cb5a39b0d1bda734915467d76a51e5a12d0b23cc69d77b99639c12cf0a527dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
